# -*- mode: ruby -*-
# vi: set ft=ruby :

# Some sources of boxes:
# https://atlas.hashicorp.com/chef 

unless Vagrant.has_plugin?("vagrant-omnibus")
  raise 'Please run `vagrant plugin install vagrant-omnibus` which enables chef as a provisioner. '
end

Vagrant.configure(2) do |config|
  config.omnibus.chef_version = "11.18.6"
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "tdi-chap04"
  config.ssh.forward_agent = true
  config.vm.provider "virtualbox" do |vb|
    # Customize the guest vm 
    vb.cpus = 2
    vb.memory = 2048
  end
  config.vm.provision "shell", inline: <<-SHELL
   # sudo apt-get update
  SHELL

  config.vm.provision "chef_client" do |chef|
    chef.chef_server_url = "https://api.opscode.com/organizations/runamok"
    chef.validation_client_name = "runamok-validator"
    chef.validation_key_path = "/etc/chef/validation.pem"
    chef.attempts = 5

    chef.log_level = "info" # "debug"
    chef.verbose_logging = true
    chef.custom_config_path = "Vagrantfile.chef"

    chef.add_role "chap4"

    # cleanup
    chef.delete_node = true
    chef.delete_client = true
end
end
